name: mental_health
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.3.3
  - pymongo=4.5.0
  - python-dotenv=1.0.0
  - numpy=1.26.0
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.17.0
  - jupyter
  - pip
  - pip:
    - sentence-transformers==2.2.2